Updated Gatekeeper Guard
metaplex/docs pull request #417
Opened 2023-03-01 15:03 UTC by araptarchis

The docs where only mentioning the Captcha challenge, which is only one of the challenges that are actually supported. I added a table of the other, more advanced options.

2023-03-25 22:17 UTC, staccDOTsol commented
It sounds like you're referring to a documentation update for a Gatekeeper Guard. What is your question or concern about this update?

2023-04-03 07:46 UTC, araptarchis commented
> It sounds like you're referring to a documentation update for a Gatekeeper Guard. What is your question or concern about this update?

No question or concern from my side, I just updated the documentation.

2023-04-26 07:25 UTC, MarkSackerberg commented
Thank you for your update @araptarchis !
As far as i know the gatekeeper technically does not has to be civic, so at least having a sentence in there mentioning it would make sense from my point of view to keep it a bit more general.

2023-07-07 20:39 UTC, samuelvanderwaal commented
Is this read to be merged or does it still need the extra sentence added? @MarkSackerberg @araptarchis

2023-07-25 10:31 UTC, lorisleiva requested changes

2023-07-25 10:31 UTC, lorisleiva commented on docs/01-programs/02-candy-machine/09-available-guards/07-gatekeeper.md
> +# Gatekeeper / Civic Pass
Please revert this as the guard is called `Gatekeeper`.

```suggestion
# Gatekeeper
```

2023-07-25 10:31 UTC, lorisleiva commented on docs/01-programs/02-candy-machine/09-available-guards/07-gatekeeper.md
> -- [Gateway React Components](https://www.npmjs.com/package/@civic/solana-gateway-react)
Any reason these links were removed?

2023-07-25 10:31 UTC, lorisleiva commented on docs/01-programs/02-candy-machine/09-available-guards/07-gatekeeper.md
> -There isn’t much to set up on the Candy Machine side but, depending on the selected Gatekeeper Network, you may need to ask the minting wallet to perform so pre-validation checks to grant them the re
Not a big fan of this change as the transition with the previous paragraph is a bit harsh. May I suggest the following instead?


> In order to add a **Gatekeeper** to your Candy Machine, you must first select a **Gatekeeper Network** which defines how user verification is performed.
> 
> There isn’t much to set up on the Candy Machine side, you simply need to provide the public key of the Gatekeeper Network of your choice and whether or not Gateway Tokens should expire after being used. Note that depending on the selected Gatekeeper Network, you may need to ask the user to perform so pre-verification checks to grant them the required Gateway Token.
> 
> Here is a list of available Gatekeeper Networks and how to get started with them.

2023-07-25 10:31 UTC, lorisleiva commented on docs/01-programs/02-candy-machine/09-available-guards/07-gatekeeper.md
> +| **Captcha Verification** ([Demo](https://getpass.civic.com))         	| Captcha check to filter bots.
```suggestion
| **Captcha Verification** ([Demo](https://getpass.civic.com))         	| Captcha check to filter bots.                                                                                                                   	| `ignREusXmGrscGNUesoU9mxfds9AiYTezUKex2PsZV6`                                  	|
```

2023-09-08 16:35 UTC, lorisleiva commented
Hi there, I'm closing this due to inactivity and the fact that we moved our docs to developers.metaplex.com (https://github.com/metaplex-foundation/developer-hub).

2023-09-08 16:35 UTC, closed without merging